In [1]:
import pandas as pd
import numpy as np

# Parameters
item_code_cleaned = pd.read_csv('cleaned_item_code.csv')

codes = item_code_cleaned['item_number'].tolist()

materials_bank = [f"Material {i}" for i in range(1, 7)]  # Materials from "Material 1" to "Material 30", (1, 31)
quantity_range = (1, 10)  # Quantity range (1 to 20)

# Create dummy BoM dataset
data_list = []

for code in codes:
    num_materials = np.random.randint(1, 4)  # Randomly choose 3-5 materials per Code
    selected_materials = np.random.choice(materials_bank, num_materials, replace=False)
    quantities = np.random.randint(quantity_range[0], quantity_range[1] + 1, num_materials)
    
    for material, quantity in zip(selected_materials, quantities):
        data_list.append({"Code": code, "Material": material, "Quantity": quantity})

# Convert to a DataFrame
bom_df = pd.DataFrame(data_list)

# Display the dummy BoM dataset
bom_df

     Code    Material  Quantity
0     011  Material 3         5
1     011  Material 5         8
2     011  Material 4         8
3     012  Material 2         8
4     012  Material 1         7
..    ...         ...       ...
677   999  Material 1         6
678   999  Material 6         5
679  1Dsy  Material 1         9
680  1Dsy  Material 5         3
681  1Dsy  Material 4         7

[682 rows x 3 columns]

In [2]:
bom_df.to_csv('bom_single_clinic.csv', index=False)